// src/kernel/irupts.zig
//
// Hardware interrupt handlers for:
//
//   • IRQ0  - PIT timer
//   • IRQ1  - PS/2 keyboard
//   • IRQ12 - PS/2 mouse
//
// Handler design goals:
//
//   • Perform only minimal interrupt-time work
//   • Update kernel state and dispatch events
//   • Delegate complex processing to subsystems
//   • Signal interrupt completion via APIC or PIC EOI
//
const vga = @import("vga.zig");
const io = @import("port_io.zig");
const conv = @import("convert.zig");
const keyboard = @import("inputs/keyboard.zig");
const task = @import("task.zig");
const config = @import("config.zig");
const scheduler = @import("scheduler.zig");
const apic = @import("apic.zig");
const mouse = @import("drivers/mouse.zig");

/// Monotonic system tick counter.
///
/// Incremented by the timer interrupt and used for scheduling,
/// sleep timing, and uptime reporting.
pub var ticks: u64 = 0;

// -----------------------------------------------------------------------------
//  IRQ0 — SYSTEM TIMER
// -----------------------------------------------------------------------------

/// Handle timer interrupts generated by the PIT or APIC timer.
///
/// Responsibilities:
///   • Advance the global system clock
///   • Update uptime statistics
///   • Wake sleeping tasks whose timers have expired
///   • Trigger scheduler preemption when enabled
///   • Acknowledge the interrupt controller
pub export fn irq0_handler() callconv(.c) void {

    // Advance the global kernel tick counter.
    ticks += 1;

    // Keep the scheduler's internal time base synchronized with
    // the global system clock.
    scheduler.manager.ticks = ticks;

    const current_ticks = ticks;

    // Update the on-screen uptime display once per second
    // (assuming a 100 Hz timer frequency).
    if (current_ticks % 100 == 0) {
        const total_seconds = current_ticks / 100;
        const minutes = @as(u32, @intCast(total_seconds / 60));
        const seconds = @as(u32, @intCast(total_seconds % 60));

        var m_buf: [16]u8 = undefined;
        var s_buf: [16]u8 = undefined;

        const m_str = conv.u32ToStr(&m_buf, minutes);
        const s_str = conv.u32ToStr(&s_buf, seconds);

        const row: u16 = 0;
        const col_start: u16 = 60;

        vga.writeStringAt(row, col_start, "Uptime: ", 0x07, 0);

        // Display elapsed minutes.
        vga.writeStringAt(row, col_start + 8, m_str, 0x0E, 0);
        const m_len = @as(u16, @intCast(m_str.len));
        vga.writeStringAt(row, col_start + 8 + m_len, "m ", 0x07, 0);

        // Display elapsed seconds.
        const s_pos = col_start + 8 + m_len + 2;
        vga.writeStringAt(row, s_pos, s_str, 0x0E, 0);
        const s_len = @as(u16, @intCast(s_str.len));
        vga.writeStringAt(row, s_pos + s_len, "s ", 0x07, 0);
    }

    // Resume any tasks whose sleep interval has expired.
    inline for (&scheduler.manager.tasks) |*maybe_task| {
        if (maybe_task.*) |*t| {
            if (t.state == .Suspended and ticks >= t.wake_tick) {
                t.state = .Ready;
            }
        }
    }

    // Allow the scheduler to perform a preemptive context switch
    // if preemption is currently enabled.
    if (scheduler.manager.yield_enabled) {
        scheduler.manager.yield();
    }

    // Acknowledge interrupt completion.
    //
    // APIC-based systems signal EOI through the local APIC,
    // while legacy systems use the master PIC command port.
    if (config.timer.use_apic) {
        apic.sendEoi();
    } else {
        io.outb(0x20, 0x20); // Master PIC EOI
    }
}

// -----------------------------------------------------------------------------
//  IRQ1 — KEYBOARD
// -----------------------------------------------------------------------------

/// Handle keyboard interrupts originating from the PS/2 controller.
///
/// Reads the pending scancode, forwards it to the keyboard subsystem,
/// and acknowledges interrupt completion.
pub export fn irq1_handler() callconv(.c) void {

    // Read the scancode from the PS/2 data port.
    const scancode = io.inb(0x60);

    // Delegate scancode processing to the keyboard driver.
    keyboard.handleScancode(scancode);

    // Notify the active interrupt controller that processing has
    // completed and the interrupt may be re-issued.
    if (config.timer.use_apic) {
        apic.sendEoi();
    } else {
        io.outb(0x20, 0x20); // Master PIC EOI
    }

    // Legacy reactive wake-up logic removed.
    // Scheduling and task wake-up are handled by the timer interrupt.
    //
    // if (task.manager.tasks[0]) |*shell| {
    //     if (shell.state == .Blocked and shell.wake_tick == 0) {
    //         shell.state = .Ready;
    //     }
    // }
}

// -----------------------------------------------------------------------------
//  IRQ12 — PS/2 MOUSE
// -----------------------------------------------------------------------------

/// Packet assembly state for incoming PS/2 mouse data.
var mouse_index: u8 = 0;

/// Temporary storage for a complete 3-byte PS/2 mouse packet.
var mouse_packet: [3]u8 = .{0, 0, 0};

var count: u8 = 0;

/// Configure the Programmable Interval Timer (PIT).
///
/// This function programs PIT channel 0 to generate periodic timer
/// interrupts at the requested frequency.
///
/// Call after PIT and mouse initialisation but before enabling
/// interrupts with sti.
pub fn init_pit(frequency: u32) void {

    // The PIT input clock operates at approximately 1.193182 MHz.
    const divisor = @as(u16, @intCast(1193182 / frequency));

    // PIT command register:
    //   Channel 0
    //   Low byte / high byte access mode
    //   Square-wave generator mode
    //   Binary counting
    io.outb(0x43, 0x36);

    // Write the divisor to PIT channel 0.
    io.outb(0x40, @as(u8, @intCast(divisor & 0xFF)));         // Low byte
    io.outb(0x40, @as(u8, @intCast((divisor >> 8) & 0xFF))); // High byte
}

/// Handle PS/2 mouse interrupts.
///
/// Mouse movement is delivered as a sequence of 3-byte packets.
/// This handler assembles complete packets, decodes movement data,
/// updates cursor state, and redraws the on-screen cursor.
pub export fn irq12_handler() callconv(.c) void {
    const byte = io.inb(0x60);

    // The first byte of every PS/2 packet must have bit 3 set.
    // If synchronisation is lost, discard bytes until a valid
    // packet boundary is found.
    if (mouse_index == 0 and (byte & 0x08) == 0) {
        sendEoi();
        return;
    }

    mouse_packet[mouse_index] = byte;
    mouse_index += 1;

    // Process the packet once all three bytes have been received.
    if (mouse_index >= 3) {
        mouse_index = 0;

        const flags = mouse_packet[0];
        var raw_x = @as(i32, mouse_packet[1]);
        var raw_y = @as(i32, mouse_packet[2]);

        // Apply sign extension using the overflow/sign bits
        // contained in the packet flags byte.
        if ((flags & 0x10) != 0) raw_x -= 256;
        if ((flags & 0x20) != 0) raw_y -= 256;

        // Clamp movement deltas to the signed 8-bit range used by
        // the mouse subsystem.
        const dx = @as(i8, @intCast(@max(-128, @min(127, raw_x))));
        const dy = @as(i8, @intCast(@max(-128, @min(127, raw_y))));

        mouse.eraseCursor();
        mouse.updatePosition(dx, dy);
        mouse.drawCursor(mouse.mouse_x, mouse.mouse_y);
    }

    sendEoi();
}

/// Signal interrupt completion to the active interrupt controller.
///
/// IRQ12 originates from the slave PIC on legacy systems, so both
/// slave and master EOIs must be issued when APIC mode is not in use.
fn sendEoi() void {
    if (config.timer.use_apic) {
        apic.sendEoi();
    } else {
        io.outb(0xA0, 0x20);
        io.outb(0x20, 0x20);
    }
}

/// Busy-wait for the specified number of timer ticks.
///
/// The processor repeatedly enters the halted state and resumes on
/// each interrupt until the requested interval has elapsed.
pub fn sleep(ticks_to_wait: u64) void {
    const start_tick = ticks;

    while (ticks - start_tick < ticks_to_wait) {
        asm volatile ("hlt");
    }
}
